### ISSUE TITLE
Failed to execute "select distinct sourcesystem_cd from i2b2metadata.i2b2" in postgres

### ISSUE THREAD

**Issue by ghost** [ThomsonReuters-LSPS/tMDataLoader#72]
Hello,
I just installed transmart1.2.5 and setup DB to work tMDataLoader1.2.4. I tried loading data and got the attached error.

please what can do to resolve this?
Thanks
![error](https://user-images.githubusercontent.com/40699827/80279500-6571e680-86fe-11ea-8ecd-95385b895d67.jpg)

**Comment by xuatiknc** [comment]
Hi,
I may guess that you are trying to use a pre-83aafb3 version (November 7th, 2016 - that's when the current last line in file sql/postgres/migrations/20140724000000000_CREATE_TM_DATALOADER_SCHEMA.sql was added). I would recommend installing tMDataLoader from branch transmart_16.3 . Do not try to install from current master branch because it contains 19.0-specific changes that are incompatible with previous versions of tranSMART.

**Comment by ghost** [comment]
Thank you. Your suggestion works for me. I only ensured the released version of the tMDataLoader fits my current version of transmart.
